<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260728113812 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_app_user_email ON app_user (email)');
        $this->addSql('CREATE TABLE commande (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, statut VARCHAR(255) NOT NULL, total NUMERIC(10, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, promo_code_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6EEAA67DA76ED395 ON commande (user_id)');
        $this->addSql('CREATE INDEX IDX_6EEAA67D2FAE4625 ON commande (promo_code_id)');
        $this->addSql('CREATE TABLE ligne_commande (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, prix_unitaire NUMERIC(10, 2) NOT NULL, commande_id INT NOT NULL, prestation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3170B74B82EA2E54 ON ligne_commande (commande_id)');
        $this->addSql('CREATE INDEX IDX_3170B74B9E45C554 ON ligne_commande (prestation_id)');
        $this->addSql('CREATE TABLE ligne_panier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, panier_id INT NOT NULL, prestation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_21691B4F77D927C ON ligne_panier (panier_id)');
        $this->addSql('CREATE INDEX IDX_21691B49E45C554 ON ligne_panier (prestation_id)');
        $this->addSql('CREATE TABLE paiement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, montant NUMERIC(10, 2) NOT NULL, statut VARCHAR(255) NOT NULL, moyen_paiement VARCHAR(50) NOT NULL, reference_externe VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, commande_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B1DC7A1E82EA2E54 ON paiement (commande_id)');
        $this->addSql('CREATE TABLE panier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_24CC0DF2A76ED395 ON panier (user_id)');
        $this->addSql('CREATE TABLE prestation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, description TEXT NOT NULL, prix NUMERIC(10, 2) NOT NULL, duree_minutes INT DEFAULT NULL, actif BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE promo_code (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, type_reduction VARCHAR(255) NOT NULL, valeur NUMERIC(10, 2) NOT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, montant_minimum NUMERIC(10, 2) DEFAULT NULL, nombre_utilisations_max INT DEFAULT NULL, nombre_utilisations_actuelles INT NOT NULL, prestation_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3D8C939E9E45C554 ON promo_code (prestation_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_promo_code_code ON promo_code (code)');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67DA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67D2FAE4625 FOREIGN KEY (promo_code_id) REFERENCES promo_code (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_commande ADD CONSTRAINT FK_3170B74B82EA2E54 FOREIGN KEY (commande_id) REFERENCES commande (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_commande ADD CONSTRAINT FK_3170B74B9E45C554 FOREIGN KEY (prestation_id) REFERENCES prestation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_panier ADD CONSTRAINT FK_21691B4F77D927C FOREIGN KEY (panier_id) REFERENCES panier (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_panier ADD CONSTRAINT FK_21691B49E45C554 FOREIGN KEY (prestation_id) REFERENCES prestation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1E82EA2E54 FOREIGN KEY (commande_id) REFERENCES commande (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE panier ADD CONSTRAINT FK_24CC0DF2A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE promo_code ADD CONSTRAINT FK_3D8C939E9E45C554 FOREIGN KEY (prestation_id) REFERENCES prestation (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67DA76ED395');
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67D2FAE4625');
        $this->addSql('ALTER TABLE ligne_commande DROP CONSTRAINT FK_3170B74B82EA2E54');
        $this->addSql('ALTER TABLE ligne_commande DROP CONSTRAINT FK_3170B74B9E45C554');
        $this->addSql('ALTER TABLE ligne_panier DROP CONSTRAINT FK_21691B4F77D927C');
        $this->addSql('ALTER TABLE ligne_panier DROP CONSTRAINT FK_21691B49E45C554');
        $this->addSql('ALTER TABLE paiement DROP CONSTRAINT FK_B1DC7A1E82EA2E54');
        $this->addSql('ALTER TABLE panier DROP CONSTRAINT FK_24CC0DF2A76ED395');
        $this->addSql('ALTER TABLE promo_code DROP CONSTRAINT FK_3D8C939E9E45C554');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE commande');
        $this->addSql('DROP TABLE ligne_commande');
        $this->addSql('DROP TABLE ligne_panier');
        $this->addSql('DROP TABLE paiement');
        $this->addSql('DROP TABLE panier');
        $this->addSql('DROP TABLE prestation');
        $this->addSql('DROP TABLE promo_code');
    }
}
